### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by asanaik** [lukasabbe/Copper-Grates-Bubble#2]
It does not work, I've tried with normal and wax variants but nothing works. I'm on 1.21.1 and have it on the server and on client.

**Comment by lukasabbe** [comment]
Have you waterlogged the grate?

**Comment by lukasabbe** [comment]
@asanaik Did this solve the problem?

**Comment by lukasabbe** [comment]
I did not answer the question, so I assume you got it to work.
